name: Flask App Tests

#The workflow will run every time when a 
#pull request is made on main branch 

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./app/
        strategy:
            matrix:
                python-version: [3.13.1]
        env:
            MODE: "dev"

        steps:
            - uses: actions/checkout@v3 # Predefined scripts 
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }} # Is taking versions defined in 'matrix' in 'strategy' step

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r ../requirements.txt
                
            - name: Test App Code
              run: python ./main_test.py